### ISSUE TITLE
对于这个应用有几个建议

### ISSUE THREAD

**Issue by fxzxmicah** [MilesChing/ThunderX#1]
感谢作者做出一个如此简洁的下载应用，非常喜欢。提两个建议，第一个是加入一个历史任务，或者下载完成任务不消失，仍然显示在下载页，方便完成任务立即打开或重新下载。另外一个是应用在很多情况下无法获取正确的下载文件名，每次都需要手动修改，希望作者修复一下，谢谢。

**Comment by MilesChing** [comment]
在即将更新的1.9.0.0版本中我加入了历史任务功能，现在在你没有删除或移动文件的情况下可以访问历史下载的文件，相信很多人和你有同样的需求。我在版本1.9.0.0中改善了扩展名的“猜测”算法并加入了推荐扩展名的功能，实际上如果服务器返回的报文和链接本身都不包含关于文件名的信息，软件这边也不好准确地得知你在下载的文件名，还是需要用户手动调节不满意的文件名。总之十分感谢你的支持和建议~
