### ISSUE TITLE
发现几点问题！

### ISSUE THREAD

**Issue by QiaoYueMeng** [MilesChing/ThunderX#33]
BT基本设置，比如随机端口，DHT等等都还没有。

可能因为DHT这些设置不完善，发现在移动宽带下面没办法下载，包括解析磁力链！

直接粘贴磁力链成功过，但是直接选中种子没有一次成功过！

trackerlist能不能自动更新呢……

感谢作者开发软件，谢谢！

**Comment by MilesChing** [comment]
已知可能导致无法连接 Peers 或 Tracker 服务器的原因：

1. 检查是否有本地安全软件阻止 Thunder X 连接网络；
1. 如果你的操作系统在 Windows 10 2004 版本及以上，在无线网络下无法通过 BitTorrent 下载，请确保 `设置 → 网络和 Internet → WLAN → 选择能够使用你的 WLAN 数据的应用` 中选择允许 Thunder X 使用 WLAN 数据；

如果这些场景不适用你的问题，请提供下载失败的磁力链或 `.torrent` 文件便于我复现问题，谢谢！

**Comment by MilesChing** [comment]
关于 DHT 协议以及在设置中开放更多功能已在日程中但还需要一定时间，关于你提到的其他两个建议请在之前单独的 issue 中详细叙述，例如需要怎样的自动更新功能，使用场景大致是怎样的？建议将这个 issue 专门用作解决下载失败的问题。

**Comment by QiaoYueMeng** [comment]
种子没办法下载，基本上都出现，你可以到btbtt.us这电影站下面试试，不知道是不是我添加种子问题，选中种子之后没有任何反应。

**Comment by QiaoYueMeng** [comment]
目前还有一个很严重的问题，五次里面遇到四次，任务99%失败，然后重新启动下载，软件奔溃，往复循环。

**Comment by MilesChing** [comment]
> 目前还有一个很严重的问题，五次里面遇到四次，任务99%失败，然后重新启动下载，软件奔溃，往复循环。

请提供下载失败的链接便于我复现问题，谢谢！

**Comment by QiaoYueMeng** [comment]
magnet:?xt=urn:btih:948AAA9510B2FA5812176FDC420DE42ECF04521E&dn=[y5y4.com]赘婿.Zhui Xu.E17-18.2021.2160P(4K).WEB-DL.H265.AAC-AIU

这个磁力，你先转成种子，是没办法添加下载的，只能添加磁力，同时下载到99%显示报警错误！

**Comment by QiaoYueMeng** [comment]
显示下载100%，报错误，并且文件夹打开里面是空的……

**Comment by MilesChing** [comment]
> 显示下载100%，报错误，并且文件夹打开里面是空的……

这里报的错误具体内容是什么？在任务详情页面或者应用程序弹出的 Toast 通知会显示错误的具体内容，方便的话请截图发到这里~

**Comment by MilesChing** [comment]
版本 [2.0.6.0](https://github.com/MilesChing/ThunderX/releases/tag/2.0.6.0) 已在应用商店可用，我尝试修复了这个问题，如果崩溃或者报错继续出现请继续提供详细错误的信息。
