### ISSUE TITLE
Add file downloads automatically via browser

### ISSUE THREAD

**Issue by nblackburn** [MilesChing/ThunderX#4]
When using the browser and clicking on a download, it would be nice if it was added automatically (but not started).

**Comment by MilesChing** [comment]
Automatically transfer download tasks (HTTP/HTTPS) from the browser to a UWP application seems impossible. I'm thinking to support this for downloading with special proxys only, like 'magnet' or 'thunderbolt'.

**Comment by MilesChing** [comment]
In the latest release #41, the URL of specific protocols will directly launch Thunder X up, ready to create a new task. For now, URLs start with 'magnet:' and 'thunder://' is supported and we will keep adding support to available types of URLs in the future, which I think is as much as what we can do on UWP today.
