### ISSUE TITLE
添加种子无法下载！

### ISSUE THREAD

**Issue by QiaoYueMeng** [MilesChing/ThunderX#40]
![image](https://user-images.githubusercontent.com/29940180/110400480-aa9ecd00-80b2-11eb-8b4d-65a7b55a68df.png)

不知道能不能看到，每个种子都是这种问题，选中之后识别不出来，点击不了创建！

**Comment by MilesChing** [comment]
你好，通过“选取文件以开始”选中的文件扩展名是否为 .torrent ？如扩展名确认是 .torrent 请把该种子文件附件到这个 issue，扩展名不是 .torrent 需要改为 .torrent 才能被识别。

**Comment by QiaoYueMeng** [comment]
[[GM-Team][国漫][吞噬星空][Swallowed Star][2020][16][AVC][GB][1080P].zip](https://github.com/MilesChing/ThunderX/files/6105496/GM-Team.Swallowed.Star.2020.16.AVC.GB.1080P.zip)

就是这个种子，基本每个种子都有这问题！

**Comment by MilesChing** [comment]
这是一个 .zip 压缩文件，请先解压它获得 .torrent 文件才能添加到任务。 Thunder X 对输入文件类型做了限制，扩展名必须为 .torrent 。

**Comment by QiaoYueMeng** [comment]
github不能上传种子，我压缩了才上传的，麻烦解压一下，我也不算小白。


 
---原始邮件---
发件人: "Qin Zhengrui"<notifications@github.com&gt;
发送时间: 2021年3月9日 10:42:29
收件人: "MilesChing/ThunderX"<ThunderX@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"桥月梦"<QYMSh@qq.com&gt;;
主题: Re: [MilesChing/ThunderX] 添加种子无法下载！ (#40)




 
这是一个 .zip 压缩文件，请先解压它获得 .torrent 文件才能添加到任务。 Thunder X 对输入文件类型做了限制，扩展名必须为 .torrent 。

**Comment by MilesChing** [comment]
确实是目前软件的问题，初步判断是文件名或路径中含有中文字符造成的，我需要进一步研究来修复这个问题。目前你可以暂时将文件改为全英文命名，我这里可以就成功打开文件了。

![image](https://user-images.githubusercontent.com/8838227/110412046-877e1880-80c6-11eb-8a59-63ff3f29c6a4.png)

**Comment by QiaoYueMeng** [comment]
好的，谢谢


 
---原始邮件---
发件人: "Qin Zhengrui"<notifications@github.com&gt;
发送时间: 2021年3月9日 11:00:36
收件人: "MilesChing/ThunderX"<ThunderX@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"桥月梦"<QYMSh@qq.com&gt;;
主题: Re: [MilesChing/ThunderX] 添加种子无法下载！ (#40)




 
确实是目前软件的问题，初步判断是文件名或路径中含有中文字符造成的，我需要进一步研究来修复这个问题。目前你可以暂时将文件改为全英文命名，我这里可以就成功打开文件了。
