### ISSUE TITLE
任务自动消失，下载记录无法保存

### ISSUE THREAD

**Issue by QiaoYueMeng** [MilesChing/ThunderX#42]
在添加种子之后，任务进度0%，关闭软件再打开，任务自动消失，下载记录也无法保存。

**Comment by MilesChing** [comment]
你好，任务和下载记录消失的问题是时常出现还是偶尔出现？或者是下载特定任务时出现？

**Comment by QiaoYueMeng** [comment]
每次出现，正在下载的任务消失，出现在添加任务，但是任务还没有数据下载下来的时候，也就是没有缓存。


下载记录消失也是每次出现，下载完成再关闭软件，再打开是没有记录的！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MilesChing/ThunderX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 下午2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MilesChing/ThunderX] 任务自动消失，下载记录无法保存 (#42)





 
你好，任务和下载记录消失的问题是时常出现还是偶尔出现？或者是下载特定任务时出现？

**Comment by MilesChing** [comment]
”正在下载的任务消失，出现在添加任务“是什么意思？

**Comment by QiaoYueMeng** [comment]
比如一个种子我刚添加，但是没有数据下载，我关闭软件，再打开这个任务是没有的！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MilesChing/ThunderX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MilesChing/ThunderX] 任务自动消失，下载记录无法保存 (#42)





 
”正在下载的任务消失，出现在添加任务“是什么意思？
