### ISSUE TITLE
下载缓存存放位置应该从C盘改为下载位置。

### ISSUE THREAD

**Issue by QiaoYueMeng** [MilesChing/ThunderX#43]
有时候C盘空间不大，一旦下载大文件，导致C盘直接占满……

 看了一下下载位置，并没有出现正在下载的片段。

**Comment by MilesChing** [comment]
你好，由于 UWP 的安全性限制，对于 Thunder X 内部许多下载器使用的文件 IO 接口来说，唯一能完美进行独写的位置即目前使用的缓存文件夹夹。因此在近几个版本暂不能实现自定义的缓存位置。如果某个驱动器空间不足，可以尝试将 Thunder X 安装位置移动到其他驱动器，这样缓存文件夹的位置也将随之移动到其他驱动器。

具体请在 设置 -> 系统 -> 存储 -> 应用和功能 中找到 Thunder X 并选择移动即可。
