### ISSUE TITLE
Torrent support

### ISSUE THREAD

**Issue by nblackburn** [MilesChing/ThunderX#5]
Adding support for torrent downloads would be great.

**Comment by MilesChing** [comment]
In the latest version #18 under developing (I will release it in several days) Torrent downloader has been embedded. For now users are allowed to pick a file as source when creating new tasks and a Torrent downloader will be created if a legal '.torrent' file is given. Downloading from magnet links is still an un-test behavior so it won't be supported in this version. But it should be OK using the same type of downloader so it will be soon delivered as well. Thanks for opening this.

**Comment by MilesChing** [comment]
Downloading using BitTorrent proxy has been fully implemented in the latest release. Feel free to open a new issue if having trouble with downloading. I‘m going to close this to mark the completion of the proposal.
